[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.2" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
mailin-embedded = { version = "^0", features = ["rtls"] }
mailparse = "0.13.5"

[dependencies.tauri]
version = "1.0.0-beta"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
